# permissions for end users to view registers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: register-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: workload-operator
    app.kubernetes.io/part-of: workload-operator
    app.kubernetes.io/managed-by: kustomize
  name: register-viewer-role
rules:
- apiGroups:
  - argocd.workload.com
  resources:
  - registers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - argocd.workload.com
  resources:
  - registers/status
  verbs:
  - get
