name: Lint

# Trigger the workflow on pull requests and direct pushes to any branch
on:
  push:
  pull_request:

jobs:
  lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    # Pull requests from the same repository won't trigger this checks as they were already triggered by the push
    if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository)
    steps:
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '~1.20'
      - name: Clone the code
        uses: actions/checkout@v3
      - name: Run linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run yamllint make target
        run: make yamllint